pinecone:
  index_name: 'hybrid-index'  #"medical-chatbot-index"
  name_space: "hybrid-namespace"  #"medical-namespace"

openai:
  model: "gpt-5-nano"

retriever:
  dim: 1024
  top_ret_doc: 3
  alpha: 0.25
  dense_model: "text-embedding-3-large"
  #batch size for upsert
  batch_size: 1
  #sleep time between upsert batches
  sleep_time: 2